apiVersion: v1
kind: Pod
metadata:
  name: mqtt-publisher
  namespace: default
  labels:
    app: mqtt-publisher
spec:
  restartPolicy: Always
  containers:
    - name: publisher
      image: swr.cn-east-3.myhuaweicloud.com/cloud-ljh-ys/mqtt-edge:v1
      command: ["python", "sensor_publisher.py"]
      env:
        - name: BROKER_HOST
          valueFrom:
            configMapKeyRef:
              name: mqtt-edge-config
              key: broker_host
        - name: BROKER_PORT
          value: "1883"
        - name: MQTT_TOPIC
          value: sensor/temperature
        - name: DEVICE_ID
          value: sensor_001
        - name: INTERVAL_SECONDS
          value: "1"
