apiVersion: v1
kind: Pod
metadata:
  name: mqtt-publisher
  namespace: default
  labels:
    app: mqtt-publisher
spec:
  restartPolicy: Always
  containers:
    - name: publisher
      image: swr.cn-east-3.myhuaweicloud.com/cloud-ljh-ys/mqtt-edge:v1
      command: ["python", "publisher.py"]
      env:
        - name: BROKER_HOST
          value: "<MOSQUITTO_ELB_IP>"
        - name: BROKER_PORT
          value: "1883"
        - name: MQTT_TOPIC
          value: edge/sensor
        - name: DEVICE_ID
          value: k3s-edge-01
        - name: INTERVAL_SECONDS
          value: "2"
